[package]
name = "rgb_reader"
version = "0.1.0"
authors = ["bulengerkacper <bulenger.kacper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
image = "0.23.12"
walkdir = "2"
orbtk = "0.3.1-alpha3"




